# Generated by Django 2.0.7 on 2018-08-02 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Readings',
            new_name='Reading',
        ),
    ]
